---
sbom-job:
  image: sbomifyhub/sbomify-action
  variables:
    TOKEN: $SBOMIFY_TOKEN
    COMPONENT_ID: 'GFcFpn8q4h'
    UPLOAD: true
    AUGMENT: true
    ENRICH: true
    SBOM_VERSION: $CI_COMMIT_SHA
    LOCK_FILE: 'poetry.lock'
    OUTPUT_FILE: "gitlab-sbom.cdx.json"

  script:
    - /sbomify.sh

  artifacts:
    paths:
      - gitlab-sbom.cdx.json
    when: always
