---
name: 'sbomify'
description: 'A GitHub Action to upload an SBOM CycloneDX or SPDX to sbomify'
author: 'sbomify'
inputs:
  component-purl:
    description: 'Override the component PURL in the SBOM (e.g., pkg:npm/@scope/name@1.0.0)'
    required: false
runs:
  using: 'docker'
  # Bump/pin this to release
  image: 'docker://sbomifyhub/sbomify-action:latest'
  env:
    COMPONENT_PURL: ${{ inputs.component-purl }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
