---
name: 'sbomify'
description: 'A GitHub Action to upload an SBOM CycloneDX or SPDX to sbomify'
author: 'sbomify'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
