"""Tests for the wizard state model and IO helpers."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from sbomify_action.cli.wizard.apply import apply_plan
from sbomify_action.cli.wizard.io import (
    WIZARD_HEADER_SENTINEL,
    WIZARD_JSON_SENTINEL_KEY,
    SbomifyJsonOwnershipError,
    WorkflowOwnershipError,
    file_has_wizard_header,
    sbomify_json_has_wizard_sentinel,
    write_sbomify_json,
    write_workflow,
)
from sbomify_action.cli.wizard.options import WizardOptions
from sbomify_action.cli.wizard.repo_facts import gather_repo_facts
from sbomify_action.cli.wizard.state import (
    DiscoveredLockfile,
    Plan,
    PlannedComponent,
    RepoFacts,
    WizardState,
    WorkspaceSnapshot,
)
from sbomify_action.exceptions import APIError


def _facts(tmp_path: Path) -> RepoFacts:
    return RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug="acme/widget",
    )


# ----------------------------------------------------------------------
# state


def test_require_api_raises_when_unset(tmp_path: Path) -> None:
    state = WizardState(facts=_facts(tmp_path))
    with pytest.raises(RuntimeError, match="before authenticate"):
        state.require_api()


def test_wizard_state_repr_summarizes(tmp_path: Path) -> None:
    state = WizardState(facts=_facts(tmp_path))
    state.workspace = WorkspaceSnapshot(products=[{"id": "p1"}])
    state.selected = [
        DiscoveredLockfile(
            path=tmp_path / "uv.lock",
            rel_path=Path("uv.lock"),
            ecosystem="python",
            suggested_name="widget-py",
        )
    ]
    rep = repr(state)
    assert "selected=1 lockfiles" in rep
    assert "workspace=<set>" in rep
    assert "api=None" in rep


def test_plan_defaults_oidc_and_skip_augmentation() -> None:
    plan = Plan()
    assert plan.credential_mode == "oidc"
    assert plan.augmentation == "skip"
    assert plan.release_strategy == "trunk"
    assert plan.create_components == []
    # Regression guard: apply.py writes sbomify.json when
    # sbomify_json_data is not None, and patch_component binds the
    # profile when contact_profile_id is truthy. Flipping either
    # default to a default_factory(dict) / default-id string would
    # silently produce data-loss / cross-workspace-bind bugs. Pin
    # both so a refactor can't introduce these failure modes
    # without test surgery.
    assert plan.sbomify_json_data is None
    assert plan.contact_profile_id is None


def test_planned_component_keeps_existing_id_optional(tmp_path: Path) -> None:
    lf = DiscoveredLockfile(
        path=tmp_path / "uv.lock",
        rel_path=Path("uv.lock"),
        ecosystem="python",
        suggested_name="widget-py",
    )
    component = PlannedComponent(lockfile=lf, name="widget-py")
    assert component.existing_id is None


# ----------------------------------------------------------------------
# options


def test_wizard_options_is_frozen(tmp_path: Path) -> None:
    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )
    with pytest.raises(Exception):  # FrozenInstanceError subclasses different bases by Python version.
        opts.token = "x"  # type: ignore[misc]


# ----------------------------------------------------------------------
# io


def test_file_has_wizard_header_detects_sentinel(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text(f"# Generated by sbomify-action.\n{WIZARD_HEADER_SENTINEL}\nname: sboms\n", encoding="utf-8")
    assert file_has_wizard_header(path) is True


def test_file_has_wizard_header_returns_false_for_missing(tmp_path: Path) -> None:
    assert file_has_wizard_header(tmp_path / "absent.yml") is False


def test_file_has_wizard_header_returns_false_for_no_sentinel(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text("name: hand-authored\non:\n  push:\n", encoding="utf-8")
    assert file_has_wizard_header(path) is False


def test_write_workflow_creates_new_file(tmp_path: Path) -> None:
    path = tmp_path / ".github" / "workflows" / "sboms.yml"
    write_workflow(path, f"# header\n{WIZARD_HEADER_SENTINEL}\nname: sboms\n")
    assert path.read_text(encoding="utf-8").startswith("# header\n")


def test_write_workflow_overwrites_existing_sentinel_file_without_bak(tmp_path: Path) -> None:
    """Sentinel-tagged files get overwritten in place — no .bak, git tracks the diff."""
    path = tmp_path / "sboms.yml"
    path.write_text(f"# old\n{WIZARD_HEADER_SENTINEL}\nname: old\n", encoding="utf-8")

    write_workflow(path, f"# new\n{WIZARD_HEADER_SENTINEL}\nname: new\n")

    assert path.read_text(encoding="utf-8").startswith("# new\n")
    # We do NOT create .bak files — the previous version is recoverable via git.
    assert not path.with_suffix(path.suffix + ".bak").exists()


def test_write_workflow_refuses_to_overwrite_handauthored(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text("name: hand-authored\non:\n  push:\n", encoding="utf-8")

    with pytest.raises(WorkflowOwnershipError, match="missing"):
        write_workflow(path, f"# new\n{WIZARD_HEADER_SENTINEL}\nname: new\n")

    # Original file unchanged; no .bak either way.
    assert path.read_text(encoding="utf-8").startswith("name: hand-authored")
    assert not path.with_suffix(path.suffix + ".bak").exists()


def test_write_sbomify_json_creates_new_file(tmp_path: Path) -> None:
    """Writing a fresh sbomify.json stamps it with the wizard sentinel."""
    import json as _json

    path = tmp_path / "sbomify.json"
    write_sbomify_json(path, {"supplier": {"name": "Acme"}})

    data = _json.loads(path.read_text(encoding="utf-8"))
    assert data["supplier"] == {"name": "Acme"}
    assert WIZARD_JSON_SENTINEL_KEY in data
    assert data[WIZARD_JSON_SENTINEL_KEY]["managed"] is True


def test_write_sbomify_json_overwrites_existing_sentinel_file(tmp_path: Path) -> None:
    """A wizard-stamped sbomify.json gets overwritten cleanly."""
    import json as _json

    path = tmp_path / "sbomify.json"
    write_sbomify_json(path, {"supplier": {"name": "v1"}})
    write_sbomify_json(path, {"supplier": {"name": "v2"}})

    data = _json.loads(path.read_text(encoding="utf-8"))
    assert data["supplier"] == {"name": "v2"}


def test_write_sbomify_json_writes_bak_on_content_change(tmp_path: Path) -> None:
    """Overwriting a wizard-stamped sbomify.json with new content stores the
    previous version as ``sbomify.json.bak`` so a user can recover hand-edits
    they made between wizard runs (the wizard's form doesn't surface every
    field — eg. licenses — and re-running would otherwise drop the lot
    silently)."""
    import json as _json

    path = tmp_path / "sbomify.json"
    write_sbomify_json(path, {"supplier": {"name": "v1"}})
    first_text = path.read_text(encoding="utf-8")

    write_sbomify_json(path, {"supplier": {"name": "v2"}})
    bak = tmp_path / "sbomify.json.bak"
    assert bak.exists()
    assert bak.read_text(encoding="utf-8") == first_text
    # And the live file got the new content.
    assert _json.loads(path.read_text(encoding="utf-8"))["supplier"] == {"name": "v2"}


def test_write_sbomify_json_no_bak_on_identical_rewrite(tmp_path: Path) -> None:
    """Re-running the wizard with no changes (dry-run-then-real, or a no-op
    re-apply) must NOT churn a fresh .bak — that would erase a prior real
    .bak the user might still need."""
    path = tmp_path / "sbomify.json"
    write_sbomify_json(path, {"supplier": {"name": "v1"}})
    write_sbomify_json(path, {"supplier": {"name": "v1"}})  # identical

    bak = tmp_path / "sbomify.json.bak"
    assert not bak.exists()


def test_write_sbomify_json_refuses_to_overwrite_handauthored(tmp_path: Path) -> None:
    """A hand-crafted sbomify.json (no wizard sentinel) must NOT be clobbered.

    Mirrors the write_workflow ownership contract — protects users
    who carried over a sbomify.json from the pre-wizard ``init``
    flow (full licenses / multi-entity suppliers / vcs_* overrides)
    against silent data loss when they re-run the wizard.
    """
    import json as _json

    path = tmp_path / "sbomify.json"
    original = {"supplier": {"name": "Handcrafted Inc"}, "licenses": ["MIT"]}
    path.write_text(_json.dumps(original), encoding="utf-8")

    with pytest.raises(SbomifyJsonOwnershipError, match="missing"):
        write_sbomify_json(path, {"supplier": {"name": "Wizard"}})

    # Original file untouched.
    assert _json.loads(path.read_text(encoding="utf-8")) == original


def test_write_sbomify_json_refuses_malformed_json(tmp_path: Path) -> None:
    """A pre-existing sbomify.json that doesn't parse is treated as 'not ours'."""
    path = tmp_path / "sbomify.json"
    path.write_text("{ not json", encoding="utf-8")

    with pytest.raises(SbomifyJsonOwnershipError):
        write_sbomify_json(path, {"supplier": {"name": "Wizard"}})


def test_write_sbomify_json_sentinel_wins_over_payload_collision(tmp_path: Path) -> None:
    """A payload key colliding with the sentinel must NOT override or
    erase it — otherwise a round-tripped or maliciously-crafted payload
    could strip the ownership marker on a future re-run.
    """
    import json as _json

    path = tmp_path / "sbomify.json"
    write_sbomify_json(
        path,
        {
            "supplier": {"name": "Acme"},
            # Payload tries to override the sentinel with a bogus value.
            WIZARD_JSON_SENTINEL_KEY: {"managed": False, "version": 999},
        },
    )

    data = _json.loads(path.read_text(encoding="utf-8"))
    # Sentinel must reflect the wizard's true ownership marker, not the
    # payload's override attempt.
    assert data[WIZARD_JSON_SENTINEL_KEY]["managed"] is True
    assert data[WIZARD_JSON_SENTINEL_KEY]["version"] == 1
    # Sentinel-helpers still recognizes the file as wizard-owned.
    assert sbomify_json_has_wizard_sentinel(path) is True
    # The non-sentinel payload still made it through.
    assert data["supplier"] == {"name": "Acme"}


def test_pick_default_workspace_key_prefers_user_default() -> None:
    """Multi-workspace PATs land on the user's default workspace,
    matching the backend's component / product scoping.
    """
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {
            "key": "sandbox",
            "name": "Sandbox",
            "members": [{"is_me": True, "is_default_team": False}],
        },
        {
            "key": "prod",
            "name": "Prod",
            "members": [{"is_me": True, "is_default_team": True}],
        },
    ]
    assert _pick_default_workspace_key(workspaces) == "prod"


def test_pick_default_workspace_key_falls_back_to_first_when_no_default() -> None:
    """When no workspace is marked default for the current user, the
    first usable key wins — the picker must always return SOMETHING
    when there's a workspace to pick.
    """
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {"key": "alpha", "members": [{"is_me": True, "is_default_team": False}]},
        {"key": "beta", "members": [{"is_me": True, "is_default_team": False}]},
    ]
    assert _pick_default_workspace_key(workspaces) == "alpha"


def test_pick_default_workspace_key_handles_empty_and_missing_members() -> None:
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    assert _pick_default_workspace_key([]) is None
    assert _pick_default_workspace_key([{"key": "lone"}]) == "lone"  # no members block
    # Non-string key entries are skipped.
    assert _pick_default_workspace_key([{"key": 42}, {"key": "real"}]) == "real"


def test_resolve_profile_workspace_uses_picked_key_when_readable(monkeypatch) -> None:
    """The common case — unscoped token, or scoped token whose workspace is
    the picked one — binds to the picked key with a single request."""
    from sbomify_action.cli.wizard.screens import authenticate as auth_mod

    calls: list[str] = []

    class _FakeClient:
        def __init__(self, base_url: str, token: str) -> None:
            pass

        def list_contact_profiles(self, key: str) -> list[dict[str, object]]:
            calls.append(key)
            return [{"id": "cp1", "name": "Default"}]

    monkeypatch.setattr(auth_mod, "SbomifyApiClient", _FakeClient)
    workspaces = [{"key": "alpha"}, {"key": "beta"}]
    team_key, profiles = auth_mod._resolve_profile_workspace("https://x", "t", workspaces, "beta")
    assert team_key == "beta"
    assert profiles[0]["id"] == "cp1"
    assert calls == ["beta"]


def test_resolve_profile_workspace_probes_when_picked_key_forbidden(monkeypatch) -> None:
    """A scoped token can't read the is_default_team-picked workspace —
    ``/api/v1/workspaces/`` isn't filtered by token scope, so the picker
    can land on a workspace the token has no access to. The resolver must
    probe the rest and bind to the workspace the token CAN read; silently
    returning [] here made the wizard show an empty profile picker and
    create new profiles in the wrong workspace."""
    from sbomify_action.cli.wizard.screens import authenticate as auth_mod
    from sbomify_action.exceptions import ForbiddenError

    class _FakeClient:
        def __init__(self, base_url: str, token: str) -> None:
            pass

        def list_contact_profiles(self, key: str) -> list[dict[str, object]]:
            if key != "scoped":
                raise ForbiddenError("Failed to list contact profiles. [403] - Forbidden")
            return [{"id": "cp-scoped", "name": "Default"}]

    monkeypatch.setattr(auth_mod, "SbomifyApiClient", _FakeClient)
    workspaces = [{"key": "default"}, {"key": "other"}, {"key": "scoped"}]
    team_key, profiles = auth_mod._resolve_profile_workspace("https://x", "t", workspaces, "default")
    assert team_key == "scoped"
    assert profiles[0]["id"] == "cp-scoped"


def test_resolve_profile_workspace_stays_put_on_transient_error(monkeypatch) -> None:
    """A transient (non-403) failure on the picked workspace must NOT trigger
    a rebind — guessing a different workspace off a 500/timeout is the exact
    wrong-workspace binding this function exists to prevent. Stay on the
    picked key with empty profiles and never probe the others."""
    from sbomify_action.cli.wizard.screens import authenticate as auth_mod
    from sbomify_action.exceptions import APIError

    probed: list[str] = []

    class _FakeClient:
        def __init__(self, base_url: str, token: str) -> None:
            pass

        def list_contact_profiles(self, key: str) -> list[dict[str, object]]:
            probed.append(key)
            if key == "picked":
                raise APIError("Failed to list contact profiles. [500] - boom")
            return [{"id": "leaked", "name": "Other"}]

    monkeypatch.setattr(auth_mod, "SbomifyApiClient", _FakeClient)
    workspaces = [{"key": "picked"}, {"key": "other"}]
    team_key, profiles = auth_mod._resolve_profile_workspace("https://x", "t", workspaces, "picked")
    assert team_key == "picked"
    assert profiles == []
    assert probed == ["picked"], "must not probe other workspaces on a transient error"


def test_resolve_profile_workspace_none_readable(monkeypatch) -> None:
    """When the picked workspace is forbidden and no other is readable, the
    resolver returns (None, []) rather than binding profile creation to a
    workspace the token can't verify."""
    from sbomify_action.cli.wizard.screens import authenticate as auth_mod
    from sbomify_action.exceptions import ForbiddenError

    class _FakeClient:
        def __init__(self, base_url: str, token: str) -> None:
            pass

        def list_contact_profiles(self, key: str) -> list[dict[str, object]]:
            raise ForbiddenError("Forbidden")

    monkeypatch.setattr(auth_mod, "SbomifyApiClient", _FakeClient)
    team_key, profiles = auth_mod._resolve_profile_workspace("https://x", "t", [{"key": "a"}, {"key": "b"}], "a")
    assert team_key is None
    assert profiles == []


def test_strip_status_codes() -> None:
    from sbomify_action.cli.wizard.screens._base import strip_status_codes

    assert (
        strip_status_codes("Failed to create product 'Notipus'. [403] - You have reached the maximum 1 products.")
        == "Failed to create product 'Notipus'. You have reached the maximum 1 products."
    )
    assert strip_status_codes("Authentication failed [401]") == "Authentication failed"
    assert strip_status_codes("no codes here") == "no codes here"
    # A bracketed number inside a (quoted) name is not an HTTP marker — the
    # regex is anchored to `` - ``/end-of-string, and here `[123]` is followed
    # by a quote, so only the real `[404]` marker is stripped.
    assert (
        strip_status_codes("Failed to create component 'Widget [123]'. [404] - not found")
        == "Failed to create component 'Widget [123]'. not found"
    )
    # A non-HTTP code (outside 1xx–5xx) is left alone.
    assert strip_status_codes("weird [999] token") == "weird [999] token"


def test_sbomify_json_has_wizard_sentinel_helpers(tmp_path: Path) -> None:
    """sbomify_json_has_wizard_sentinel covers absent / malformed / list / dict."""
    assert sbomify_json_has_wizard_sentinel(tmp_path / "absent.json") is False

    bad = tmp_path / "bad.json"
    bad.write_text("not json", encoding="utf-8")
    assert sbomify_json_has_wizard_sentinel(bad) is False

    list_top = tmp_path / "list.json"
    list_top.write_text('["not", "an", "object"]', encoding="utf-8")
    assert sbomify_json_has_wizard_sentinel(list_top) is False

    no_sentinel = tmp_path / "no-sent.json"
    no_sentinel.write_text('{"supplier": {"name": "x"}}', encoding="utf-8")
    assert sbomify_json_has_wizard_sentinel(no_sentinel) is False

    with_sentinel = tmp_path / "sent.json"
    with_sentinel.write_text('{"' + WIZARD_JSON_SENTINEL_KEY + '": {}}', encoding="utf-8")
    assert sbomify_json_has_wizard_sentinel(with_sentinel) is True


# ----------------------------------------------------------------------
# P1: existing sbomify.json detection + non-dead-ending apply


def test_gather_repo_facts_detects_existing_sbomify_json(tmp_path: Path) -> None:
    """has_sbomify_json reflects whether a repo-root sbomify.json exists."""
    assert gather_repo_facts(tmp_path).has_sbomify_json is False

    (tmp_path / "sbomify.json").write_text('{"supplier": {"name": "Acme"}}', encoding="utf-8")
    assert gather_repo_facts(tmp_path).has_sbomify_json is True


def test_repo_facts_has_sbomify_json_defaults_false(tmp_path: Path) -> None:
    """The dataclass default keeps existing construct sites working."""
    assert _facts(tmp_path).has_sbomify_json is False


def test_apply_keeps_handauthored_sbomify_json_and_still_writes_workflow(tmp_path: Path) -> None:
    """A pre-existing non-wizard sbomify.json must NOT dead-end apply.

    Before the fix, apply raised on the ownership check and never wrote the
    workflow. Now it keeps the user's file untouched (the action reads it at
    run time), logs a warning, and proceeds to write the workflow + create
    components.
    """
    # Hand-authored sbomify.json with a field the wizard form doesn't surface
    # (``licenses``) — proving we never clobber/strip it.
    handauthored = {"supplier": {"name": "Lithium Project"}, "licenses": ["MIT"]}
    json_path = tmp_path / "sbomify.json"
    json_path.write_text(json.dumps(handauthored), encoding="utf-8")

    facts = RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug="acme/widget",
        has_sbomify_json=True,
    )
    state = WizardState(facts=facts)
    state.api = MagicMock()  # not exercised: no product, no components
    state.workspace = WorkspaceSnapshot()
    state.plan = Plan(augmentation="json_config", sbomify_json_data={"supplier": {"name": "edited"}})

    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )

    logs: list[tuple[str, str]] = []
    apply_plan(state, opts, log=lambda kind, msg: logs.append((kind, msg)))

    # The hand-authored file is byte-for-byte preserved (no sentinel injected,
    # licenses intact).
    assert json.loads(json_path.read_text(encoding="utf-8")) == handauthored
    # A warning was surfaced, not a fatal error.
    assert any(kind == "warning" and "wizard" in msg.lower() for kind, msg in logs)
    # The workflow still got written — apply did not dead-end.
    assert (tmp_path / ".github" / "workflows" / "sboms.yml").is_file()


def test_apply_writes_sbomify_json_when_absent(tmp_path: Path) -> None:
    """With no pre-existing file, apply writes a wizard-stamped sbomify.json."""
    facts = RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug="acme/widget",
        has_sbomify_json=False,
    )
    state = WizardState(facts=facts)
    state.api = MagicMock()
    state.workspace = WorkspaceSnapshot()
    state.plan = Plan(augmentation="json_config", sbomify_json_data={"supplier": {"name": "Acme"}})

    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )

    apply_plan(state, opts)

    written = json.loads((tmp_path / "sbomify.json").read_text(encoding="utf-8"))
    assert written["supplier"] == {"name": "Acme"}
    assert WIZARD_JSON_SENTINEL_KEY in written  # wizard stamped it for future ownership


def test_apply_creates_component_with_bom_type(tmp_path: Path) -> None:
    """apply_plan must create components with component_type='bom' (the backend
    enum is {bom, document}; the old 'sbom' 422'd). Pins the apply.py call-site
    directly — the other component-type tests cover the client + yocto facade,
    not this path."""
    facts = RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug="acme/widget",
    )
    state = WizardState(facts=facts)
    api = MagicMock()
    api.get_or_create_component.return_value = ("comp-id-1", True)
    state.api = api
    state.workspace = WorkspaceSnapshot()
    lockfile = DiscoveredLockfile(
        path=tmp_path / "uv.lock", rel_path=Path("uv.lock"), ecosystem="python", suggested_name="widget"
    )
    state.plan = Plan(create_components=[PlannedComponent(lockfile=lockfile, name="widget")], augmentation="skip")

    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )

    apply_plan(state, opts)

    api.get_or_create_component.assert_called_once()
    assert api.get_or_create_component.call_args.kwargs.get("component_type") == "bom"


# ----------------------------------------------------------------------
# apply: OIDC trusted-publisher auto-registration


def _oidc_apply_state(
    tmp_path: Path,
    *,
    credential_mode: str = "oidc",
    visibility: str = "public",
    slug: str | None = "acme/widget",
    names: tuple[str, ...] = ("widget",),
) -> tuple[WizardState, MagicMock]:
    """Build a WizardState + mock api ready for apply_plan, with ``names``
    components and OIDC defaults. The mock's create_oidc_binding returns True
    (created) by default — tests override it for 409/error paths."""
    facts = RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug=slug,
        visibility=visibility,  # type: ignore[arg-type]
    )
    state = WizardState(facts=facts)
    api = MagicMock()
    api.get_or_create_component.side_effect = [(f"comp-{i}", True) for i in range(len(names))]
    api.create_oidc_binding.return_value = True
    state.api = api
    state.workspace = WorkspaceSnapshot()
    state.plan = Plan(
        create_components=[
            PlannedComponent(
                lockfile=DiscoveredLockfile(
                    path=tmp_path / f"{n}.lock", rel_path=Path(f"{n}.lock"), ecosystem="python", suggested_name=n
                ),
                name=n,
            )
            for n in names
        ],
        credential_mode=credential_mode,  # type: ignore[arg-type]
        augmentation="skip",
    )
    return state, api


def _real_opts(tmp_path: Path) -> WizardOptions:
    """Build WizardOptions for a real apply (dry_run=False).

    The OIDC / API-mutation tests assert on call counts to the mock
    api, so they need the real apply path. A real apply also writes
    the workflow file under ``tmp_path/.github/workflows/`` which the
    pytest tmp_path fixture cleans up after the test exits.

    (The OIDC tests were originally written against an earlier
    contract where ``dry_run=True`` still made API calls but skipped
    file writes. That contract was tightened — dry-run now skips
    every mutation — so this helper now hands back the non-dry-run
    options the tests actually need.)
    """
    return WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )


def test_apply_registers_oidc_binding_per_component(tmp_path: Path) -> None:
    state, api = _oidc_apply_state(tmp_path, names=("a", "b"))  # default visibility="public"

    apply_plan(state, _real_opts(tmp_path))

    assert api.create_oidc_binding.call_count == 2
    # Each call sends just the repo slug (no GitHub IDs, no token).
    bound_slugs = {call.args[1] for call in api.create_oidc_binding.call_args_list}
    assert bound_slugs == {"acme/widget"}
    assert state.oidc_bindings_registered == 2
    assert state.oidc_binding_note is None


def test_apply_skips_oidc_binding_in_token_mode(tmp_path: Path) -> None:
    state, api = _oidc_apply_state(tmp_path, credential_mode="token")

    apply_plan(state, _real_opts(tmp_path))

    api.create_oidc_binding.assert_not_called()
    assert state.oidc_bindings_registered == 0
    assert state.oidc_binding_note is None


def test_apply_oidc_binding_409_counts_as_registered(tmp_path: Path) -> None:
    """An already-bound repo (client returns False) still counts as registered
    and leaves no note — re-running the wizard shows success, not a warning."""
    state, api = _oidc_apply_state(tmp_path)
    api.create_oidc_binding.return_value = False  # already bound

    apply_plan(state, _real_opts(tmp_path))

    assert state.oidc_bindings_registered == 1
    assert state.oidc_binding_note is None


def test_apply_oidc_binding_failure_is_warning_not_fatal(tmp_path: Path) -> None:
    state, api = _oidc_apply_state(tmp_path)
    api.create_oidc_binding.side_effect = APIError("Failed to register trusted publisher [404] - nope")

    logs: list[tuple[str, str]] = []
    # Must NOT raise — a binding failure can't sink the whole apply.
    apply_plan(state, _real_opts(tmp_path), log=lambda kind, msg: logs.append((kind, msg)))

    # Component was still created (the failure is isolated to the binding step).
    assert state.component_ids
    assert state.oidc_binding_note is not None
    assert "404" in state.oidc_binding_note
    assert any(kind == "warning" and "trusted publisher" in msg.lower() for kind, msg in logs)


def test_apply_private_repo_registers_by_name(tmp_path: Path) -> None:
    """A private repo registers by name exactly like a public one — no GitHub
    token, no ID resolution. The backend defers ID pinning to the first publish,
    so the wizard's side is identical regardless of visibility."""
    state, api = _oidc_apply_state(tmp_path, visibility="private")

    apply_plan(state, _real_opts(tmp_path))

    assert api.create_oidc_binding.call_count == 1
    assert api.create_oidc_binding.call_args.args[1] == "acme/widget"
    assert state.oidc_bindings_registered == 1
    assert state.oidc_binding_note is None


def test_apply_skips_oidc_binding_without_repo_slug(tmp_path: Path) -> None:
    state, api = _oidc_apply_state(tmp_path, slug=None)

    apply_plan(state, _real_opts(tmp_path))

    api.create_oidc_binding.assert_not_called()
    assert state.oidc_binding_note is not None


def test_apply_oidc_partial_success_tracks_failed_components(tmp_path: Path) -> None:
    """When some bindings succeed and some fail, only the failed components
    end up in state.oidc_failed_components — the Done screen's manual-fallback
    panel lists only those, not the already-bound ones."""
    state, api = _oidc_apply_state(tmp_path, names=("a", "b", "c"))

    # Per-component: comp-0 newly registered (True), comp-1 already bound
    # (False), comp-2 raises. Keyed by component id rather than call order
    # because the per-component loop runs in parallel and call ordering is
    # not deterministic.
    def _side_effect(comp_id: str, _slug: str) -> bool:
        if comp_id == "comp-0":
            return True
        if comp_id == "comp-1":
            return False
        raise APIError("Failed to register trusted publisher [404] - not owner/admin")

    api.create_oidc_binding.side_effect = _side_effect

    apply_plan(state, _real_opts(tmp_path))

    # Two components ended up bound (newly + already), one failed.
    assert state.oidc_bindings_registered == 2
    assert state.oidc_newly_registered == 1
    assert len(state.oidc_failed_components) == 1
    failed_rel = next(iter(state.oidc_failed_components))
    # comp-2 corresponds to the third component, whose lockfile is c.lock.
    assert failed_rel == Path("c.lock")
    # Partial success surfaces both an Applied summary line AND a note so Done
    # routes to manual-fallback for the failed components.
    assert any("2/3" in line for line in state.applied)
    assert state.oidc_binding_note is not None
    assert "404" in state.oidc_binding_note


def test_apply_oidc_distinguishes_newly_registered_from_already_bound(tmp_path: Path) -> None:
    """The 201/409 split is exposed on state so Done's success message can say
    'registered X new; Y already bound' instead of falsely claiming N new."""
    state, api = _oidc_apply_state(tmp_path, names=("a", "b", "c"))

    # comp-0 newly registered (201); comp-1, comp-2 already bound (409).
    # Keyed by id rather than call order: per-component loop runs in parallel.
    def _side_effect(comp_id: str, _slug: str) -> bool:
        return comp_id == "comp-0"

    api.create_oidc_binding.side_effect = _side_effect

    apply_plan(state, _real_opts(tmp_path))

    assert state.oidc_bindings_registered == 3
    assert state.oidc_newly_registered == 1
    # The Applied summary mentions BOTH counts so the user knows what was done.
    assert any("1 new" in line and "2 already" in line for line in state.applied)


def test_apply_all_oidc_bindings_already_existed_does_not_claim_registration(tmp_path: Path) -> None:
    """A re-run where every binding already exists (all 409s) must not claim
    'Registered N component(s)' — that misleads the user about what changed."""
    state, api = _oidc_apply_state(tmp_path, names=("a", "b"))
    api.create_oidc_binding.return_value = False  # every call → already bound

    apply_plan(state, _real_opts(tmp_path))

    assert state.oidc_bindings_registered == 2
    assert state.oidc_newly_registered == 0
    # Summary should say "already set", not "registered N".
    matching = [line for line in state.applied if "trusted publisher" in line.lower()]
    assert matching
    assert any("already" in line for line in matching)
    assert not any("registered trusted publisher (acme/widget) for 2 component(s)" in line for line in matching)


def test_apply_resets_state_between_runs(tmp_path: Path) -> None:
    """A user pressing Back after a partial-fail and re-running apply must
    start from a clean slate — without the reset, oidc_binding_note from
    the first run survives the successful retry and Done shows the manual
    fallback for a successful binding."""
    state, api = _oidc_apply_state(tmp_path)
    # First run: binding fails — leaves a note.
    api.create_oidc_binding.side_effect = APIError("Failed to register trusted publisher [500]")
    apply_plan(state, _real_opts(tmp_path))
    assert state.oidc_binding_note is not None
    first_applied = list(state.applied)

    # Second run: binding succeeds — note must be cleared, applied must not duplicate.
    api.create_oidc_binding.side_effect = None
    api.create_oidc_binding.return_value = True
    api.get_or_create_component.side_effect = [("comp-0", True)]
    apply_plan(state, _real_opts(tmp_path))

    assert state.oidc_binding_note is None
    assert state.oidc_bindings_registered == 1
    assert state.oidc_failed_components == {}
    # Applied entries from the first run shouldn't accumulate.
    assert len(state.applied) < 2 * len(first_applied)


def test_apply_dry_run_sets_is_dry_run_flag_and_no_real_binding(tmp_path: Path) -> None:
    """Dry-run must mark state so Done can render preview UI; it must NOT
    increment oidc_bindings_registered (which would route Done to the success
    panel falsely claiming a binding was made)."""
    state, api = _oidc_apply_state(tmp_path)
    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=True,
    )

    apply_plan(state, opts)

    assert state.is_dry_run is True
    api.create_oidc_binding.assert_not_called()
    # Bindings counter must stay zero — Done branches on this to pick the
    # success card vs the dry-run preview panel.
    assert state.oidc_bindings_registered == 0
    # But Done needs to know SOMETHING about the would-be binding, so a note
    # carries the preview text.
    assert state.oidc_binding_note is not None
    assert "[dry-run]" in state.oidc_binding_note


def test_apply_dry_run_records_would_be_writes_in_state(tmp_path: Path) -> None:
    """Dry-run's "[dry-run] Would write X" log lines must also appear on
    state.written_files so Done's Wrote/would-write summary lists them. Without
    this the Applied panel goes silent about the workflow file even though
    the apply log just said it would be written."""
    state, _api = _oidc_apply_state(tmp_path)
    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=True,
    )

    apply_plan(state, opts)

    # Workflow path is always written in dry-run preview.
    assert any(p.name == "sboms.yml" for p in state.written_files)


def test_apply_workflow_emission_uses_created_product_id(tmp_path: Path) -> None:
    """When the user picked 'create new product', apply must pass the
    newly-created product's id (state.created_product_id) to the workflow
    emitter — otherwise tag-strategy workflows silently drop PRODUCT_RELEASE
    because plan.use_product_id stays None on the create-new path."""
    state, api = _oidc_apply_state(tmp_path, credential_mode="token")
    state.plan.create_product = "Acme Widget"
    state.plan.release_strategy = "tag"
    api.get_or_create_product.return_value = ({"id": "prod-NEW", "name": "Acme Widget"}, True)

    apply_plan(state, _real_opts(tmp_path))

    workflow_file = tmp_path / ".github" / "workflows" / "sboms.yml"
    assert workflow_file.exists()
    content = workflow_file.read_text()
    # PRODUCT_RELEASE must reference the newly-created product id, not be absent.
    assert "PRODUCT_RELEASE: '[\"prod-NEW:" in content


def test_pick_default_workspace_key_prefers_the_new_flag() -> None:
    """The backend serves is_default_workspace beside the deprecated name."""
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {"key": "sandbox", "members": [{"is_me": True, "is_default_workspace": False, "is_default_team": False}]},
        {"key": "prod", "members": [{"is_me": True, "is_default_workspace": True, "is_default_team": True}]},
    ]
    assert _pick_default_workspace_key(workspaces) == "prod"


def test_pick_default_workspace_key_still_reads_the_old_flag_alone() -> None:
    """Against a backend that has not shipped the new name yet."""
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {"key": "sandbox", "members": [{"is_me": True, "is_default_team": False}]},
        {"key": "prod", "members": [{"is_me": True, "is_default_team": True}]},
    ]
    assert _pick_default_workspace_key(workspaces) == "prod"


def test_pick_default_workspace_key_trusts_the_new_flag_over_the_old() -> None:
    """If they ever disagree, the name that is not being retired wins."""
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {"key": "sandbox", "members": [{"is_me": True, "is_default_workspace": True, "is_default_team": False}]},
        {"key": "prod", "members": [{"is_me": True, "is_default_workspace": False, "is_default_team": True}]},
    ]
    assert _pick_default_workspace_key(workspaces) == "sandbox"


def test_pick_default_workspace_key_survives_the_old_flag_being_dropped() -> None:
    """The sunset case. Before this, every membership read False and the
    picker silently fell through to the first workspace in the list."""
    from sbomify_action.cli.wizard.screens.authenticate import _pick_default_workspace_key

    workspaces = [
        {"key": "sandbox", "members": [{"is_me": True, "is_default_workspace": False}]},
        {"key": "prod", "members": [{"is_me": True, "is_default_workspace": True}]},
    ]
    assert _pick_default_workspace_key(workspaces) == "prod"
