---
name: Docker Build/Checks

on:
  push:
    branches:
      - master
    tags:
      - v*.*
jobs:
  build:
    name: Docker Build/Checks
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Simulate GitHub Actions run.
      # Change `@master` for the hash you want to test.
      - uses: sbomify/github-action@master
        name: Test Run
        env:
          TOKEN: placeholder
          COMPONENT_ID: placeholder
          UPLOAD: false
          SBOM_FILE: tests/test-data/syft.cdx.json
